### PR TITLE
Issue70

### LINKED ISSUE #46: Krona charts
- generate output in krona acceptable format
- create krona HTML reports like this:
image
- Another example --> https://hpcnihapps.cit.nih.gov/krona/sVHVgr4c0PqyvvDbb9ODxwgC.html?dataset=0&node=0&collapse=false&color=true&depth=2&font=12&key=true

### LINKED ISSUE #70: grubbers does not allow `--limit` < 1 GiB
- [ ] add output file argument
- [ ] update documentation accordingly
- [ ] limit can be float .. not just integer

### LINKED ISSUE #71: `-z` the only duplicates option for `mimeo` is not correctly implemented.
Observations:
- duplicates are 2 and only 2 files are shown .. expectation is 3 files as original file should always be reported. This is likely when the original is owned by a different uid.
- `-z` should only filter files out which do not have duplicates .. not filter out the original file as well

Scenario:
- original file "a"
- copied to "b"
- "b" is then hardlinked to "c"
- "c" is then copied to "d"
- "d" is hardlinked to "e" and "f"

What will happen:
- "a" through "f" all will have the same top_hash and bottom_hash, same size and account for 3 inodes
- Hence, this should be 1 original + 2 duplicates even though you have 6 total files.
- basically duplicate 2 duplicate inodes account for 6 files... so dup_bytes should by X 2 while `usurp` should replace 5 files with hard links

### LINKED ISSUE #75: Total sizes of folders do not add up
Observations from `du`:
- empty folder use up 4 kilobytes
- stat size of file is not the same as `du` size of the file .. (it is same as the `ls` size of the file)
- cumulative "size" underestimates `du -hs` size
- can this be fixed?? ... look at __st_blocks__ and __st_blksize__

### LINKED ISSUE #76: Bug with files with future timestamp
Files with future timestamp result in negative age. Fix by overriding it to be set to zero

### PR DESCRIPTION
**Pull request by kopardev**
## Changes

- adding `requirements.txt` for easy creation of environment in "spacesavers2" docker (fix #68, @kopardev)
- `grubbers` `--limit` can be < 1 GiB (float) fix #70 
- `grubbers` has new `--outfile` argument.
- `grubbers` output file format changed. New original file column added..
- `blamematrix` has now been moved into `mimeo`.
- `mimeo` `--duplicateonly` logic fix #71
- `mimeo` files.gz always includes the original file as the first one in the filelist.
- `mimeo` now has kronatools compatible output. ktImportText is also run if in PATH to generate HTML report for duplicates only. (fix #46, @kopardev)
- `e2e` overhauled, improved and well commented.
- documentation updated.
- total size now closely resemble `df` results fix #75
- `ls` size is not "size" and `du` size is called "calculated_size" in the new FileDetails object.
- files with future timestamps are handles correctly (fix #76, @kopardev)

### CODE REVIEW

**Comment by kelly-sovacool** [comment]
Currently, the output files from catalog, grubbers, and mimeo all start with a common prefix to encode the date, input directory, and user. However, the blame matrix is always called `blamematrix.tsv` -- should this file instead be renamed to include the same common prefix as the other files?

**Comment by kelly-sovacool** [comment]
I fixed an issue in the e2e docs ([bdee6d3](https://github.com/CCBR/spacesavers2/pull/74/commits/bdee6d3d5007e057dd10109942fe674b4afdc0a5)) and also made minor updates to the changelog notes -- e.g. succinctly describing issue 71 so users can get the gist of the fix without going to that issue.

**Review by kelly-sovacool — APPROVED** [review]
I ran `spacesavers2_e2e` on a few different directories. Results all look good, especially liking the krona reports.

I ran `spacesavers2_grubbers --limit 0` separately, as none of the directories I tested had duplicate files over the default 5 GiB. It worked as expected.

I wonder if `e2e` should have also have a limit argument to pass on to grubbers with the same default value?

**Comment by kopardev** [comment]
> I wonder if `e2e` should have also have a limit argument to pass on to grubbers with the same default value?

It [does](https://github.com/CCBR/spacesavers2/blob/1e57b5d05daa9f9e59287acab1267b4fc88083aa/spacesavers2_e2e#L17)

**Comment by kopardev** [comment]
> I fixed an issue in the e2e docs ([bdee6d3](https://github.com/CCBR/spacesavers2/pull/74/commits/bdee6d3d5007e057dd10109942fe674b4afdc0a5)) and also made minor updates to the changelog notes -- e.g. succinctly describing issue 71 so readers can get the gist of the fix without going to that issue.

Further updated docs (f72923a)

**Comment by kopardev** [comment]
> Currently, the output files from catalog, grubbers, and mimeo all start with a common prefix to encode the date, input directory, and user. However, the blame matrix is always called `blamematrix.tsv` -- should this file instead be renamed to include the same common prefix as the other files?

Done in 615f1ca .

**Comment by kopardev** [comment]
Also, fixex #64

**Pull request merged**
